# Generated by Django 3.2.4 on 2022-02-25 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooksmodel',
            name='gender',
            field=models.BooleanField(default=False, verbose_name='Female'),
            preserve_default=False,
        ),
    ]
