# Generated by Django 3.2.4 on 2022-02-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_ebooksmodel_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeVideosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('audio', models.FileField(upload_to='audios/')),
            ],
        ),
    ]
