# Generated by Django 3.2.4 on 2022-02-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_mergevideosmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebooksmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='ebooksmodel',
            name='title',
        ),
    ]
