# Generated by Django 3.2.4 on 2022-02-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20220225_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebooksmodel',
            name='pdf',
        ),
        migrations.AddField(
            model_name='ebooksmodel',
            name='transcript',
            field=models.FileField(default='Transcript', upload_to='transcripts/'),
        ),
    ]
