# Generated by Django 3.2.4 on 2022-02-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20220225_2026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EBooksModel',
            new_name='TranscriptsModel',
        ),
    ]
